# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"extract_100k": "00_core.ipynb",
         "wc_py": "00_core.ipynb",
         "wc_sys": "00_core.ipynb",
         "lsdir": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://antonbabkin.github.io/ig_format/"

git_url = "https://github.com/antonbabkin/ig_format/tree/master/"

def custom_doc_links(name): return None
